[application]
port = 8001

[database]
host = "localhost"
port = 5433
username = "postgres"
password = "password"
database_name = "newsletter"

[email_client]
base_url = "localhost"
sender_email = "test@gmail.com"
# This only sets the development version, the production token will be stored
# outside of version control since it is a sensitive secret.
authorization_token = "my-secret-token"
